using System.Text.Json.Serialization;

namespace ExamAssessmentSystem.Models
{
    public enum UserRole
    {
        Student,
        Teacher
    }

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;

        [JsonConverter(typeof(JsonStringEnumConverter))]
        public UserRole Role { get; set; }

        // Navigation property for submissions if this user is a student
        [JsonIgnore]
        public ICollection<Submission> Submissions { get; set; } = new List<Submission>();
    }

    public class Exam
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public decimal TotalMarks { get; set; }

        // Relationships
        public ICollection<Rubric> Rubrics { get; set; } = new List<Rubric>();
        [JsonIgnore]
        public ICollection<Submission> Submissions { get; set; } = new List<Submission>();
    }

    public class Rubric
    {
        public int Id { get; set; }
        public int ExamId { get; set; }
        public string CriterionDescription { get; set; } = string.Empty;
        public decimal PointValue { get; set; }

        // Navigation property back to Exam
        [JsonIgnore]
        public Exam Exam { get; set; } = null!;
    }

    public class Submission
    {
        public int Id { get; set; }
        public int ExamId { get; set; }
        public int StudentId { get; set; }
        
        // Stores canvas vector path logs as JSON string
        public string RawStrokeJson { get; set; } = string.Empty;
        
        // Translated OCR or transcribed handwritten text
        public string TranslatedText { get; set; } = string.Empty;
        
        // Markdown explanation generated by the Semantic Kernel Grading Agent
        public string AIGradingLog { get; set; } = string.Empty;
        
        // Finalized evaluation score approved or edited by human instructor
        public decimal ApprovedScore { get; set; }
        
        // Status flag checking human-in-the-loop validation
        public bool IsApproved { get; set; }

        // Navigation properties
        public Exam Exam { get; set; } = null!;
        public User Student { get; set; } = null!;
    }
}
